server:
  port: 8763
spring:
  application:
    name: spring-cloud-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
     url: jdbc:mysql://192.168.9.178:44417/spring_quartz?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
     username: root
     password: zhiyeDEV654321
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:
        enabled: true #监控台的开关 true开启 false关闭
        url-pattern: /myDruid/*
        login-username: admin
        login-password: 123456
        # 添加IP白名单
        #allow:
        # 添加IP黑名单，当白名单和黑名单重复时，黑名单优先级更高
        #deny:
      web-stat-filter:
        url-pattern: /* # 添加过滤规则
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/zydruid/*"
        profile-enable: true #能够监控单个url调用的sql列表
        session-stat-enable: true  #session统计功能
      filter:
        stat:
          log-slow-sql: true #是否开启慢sql
          slow-sql-millis: 1000
          merge-sql: false #是否开启合并sql
        wall:
          config:
            multi-statement-allow: true
          enabled: true #是否打开sql防火墙
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
mybatis:
  type-aliases-package: com.my.model #配置别名
  mapperLocations: classpath*:mapper/*.xml #配置xml扫描路径
  configuration:
    mapUnderscoreToCamelCase: true #将数据库中的字段转换为驼峰命名的模型对象
